import webpack from "webpack";
import MiniCssExtractPlugin from "mini-css-extract-plugin";
import {createCssLoader} from "../loaders/cssLoader";

export const createVanillaExtractRule = (): webpack.RuleSetRule => {
    return {
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
            MiniCssExtractPlugin.loader,
            createCssLoader({
                url: false, // Required as image imports should be handled via JS/TS import statements
            }),
        ]
    };
}